all:
  hosts:
    web01:
      ansible_host: 3.231.159.119
    web02:
      ansible_host: 44.202.210.231
    db01:
      ansible_host: 44.202.76.158

  children:
    Webservers:
      hosts:
        web01:
        web02:
    Dbservers:
      hosts:
        db01:
    Dcorigin:
      children:
        Webservers:
        Dbservers:
