---
- name: Update APT package manager and install Apache2
  hosts: Webservers
  become: yes
  tasks:
    - name: Update apt package manager
      apt:
        update_cache: yes

    - name: Upgrade all apt packages
      apt:
        upgrade: dist

    - name: Install Apache2
      apt:
        name: apache2
        state: latest

    - name: Ensure Apache2 is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

- name: Install and start Nginx
  hosts: Dbservers
  become: yes
  tasks:
    - name: Install Nginx (Debian-based systems)
      apt:
        name: nginx
        state: present
      tags: Nginx installing
      when: ansible_os_family == "Debian"
