all:
  hosts:
    web01:
      ansible_host: 100.25.20.239
    web02:
      ansible_host: 18.207.3.96
    db01:
      ansible_host: 35.153.79.214

  children:
    Webservers:
      hosts:
        web01:
        web02:
    Dbservers:
      hosts:
        db01:
    Dcorigin:
      children:
        Webservers:
        Dbservers:
